import{a as L,S as w,i as l}from"./assets/vendor-MjawMu3A.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const S="53452930-453d1b75f98a5875cf6a66d5c";async function d(s,o){return await L("https://pixabay.com/api/",{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})}const v=document.querySelector(".gallery"),f=document.querySelector(".loader");function u(s){return s.map(({webformatURL:t,largeImageURL:a,tags:e,likes:r,views:i,comments:y,downloads:b})=>`<li class="gallery-item">
      <a class="big-img" href="${a}"><img src="${t}" alt="${e}" width="360px" height="152px" /></a>
      <div class="info">
      <p class="info-descr"><b>Likes:</b> ${r}</p>
      <p class="info-descr"><b>Views:</b> ${i}</p>
      <p class="info-descr"><b>Comments:</b> ${y}</p>
      <p class="info-descr"><b>Downloads:</b> ${b}</p>
      </div>
      </li>`).join("")}function $(){v.innerHTML=""}function q(){f.hidden=!1}function p(){f.hidden=!0}const C=document.querySelector(".form"),h=document.querySelector(".form-input"),n=document.querySelector("#load-btn"),m=document.querySelector(".gallery"),g=new w(".gallery a",{captionsData:"alt",captionDelay:250});C.addEventListener("submit",M);n.addEventListener("click",P);n.classList.replace("search-btn","load-btn-hidden");p();let c=1;async function M(s){s.preventDefault();const o=h.value;$(),q();try{const t=await d(o,c);t.data.hits.length===0?l.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}):(m.innerHTML=u(t.data.hits),g.refresh(),n.classList.replace("load-btn-hidden","search-btn"))}catch(t){l.show({message:`${t}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{p()}}async function P(s){c+=1,n.disabled=!0;try{const o=h.value,t=await d(o,c),a=Math.floor(t.data.total/t.data.hits.length);m.insertAdjacentHTML("beforeend",u(t.data.hits)),g.refresh(),c>=a&&n.classList.replace("search-btn","load-btn-hidden")}catch(o){l.show({message:`${o}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{n.disabled=!1}}
//# sourceMappingURL=index.js.map
