import{a as C,S as q,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const v="53452930-453d1b75f98a5875cf6a66d5c";async function f(o,e){return await C("https://pixabay.com/api/",{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})}const d=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector("#load-btn"),m=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){return o.map(({webformatURL:n,largeImageURL:c,tags:t,likes:r,views:s,comments:w,downloads:S})=>`<li class="gallery-item">
      <a class="big-img" href="${c}"><img src="${n}" alt="${t}" width="360px" height="152px" /></a>
      <div class="info">
      <p class="info-descr"><b>Likes:</b> ${r}</p>
      <p class="info-descr"><b>Views:</b> ${s}</p>
      <p class="info-descr"><b>Comments:</b> ${w}</p>
      <p class="info-descr"><b>Downloads:</b> ${S}</p>
      </div>
      </li>`).join("")}function M(o){d.innerHTML=g(o),m.refresh()}function $(o){d.insertAdjacentHTML("beforeend",g(o)),m.refresh()}function B(){d.innerHTML=""}function y(){h.hidden=!1}function u(){h.hidden=!0}function b(){p.classList.replace("load-btn-hidden","search-btn")}function L(){p.classList.replace("search-btn","load-btn-hidden")}function P(){const o=document.querySelectorAll(".gallery-item"),e=o[o.length-15];if(!e)return;const n=e.getBoundingClientRect().top;window.scrollBy({top:n,behavior:"smooth"})}const k=document.querySelector(".form"),x=document.querySelector(".form-input"),H=document.querySelector("#load-btn");document.querySelector(".gallery");k.addEventListener("submit",O);H.addEventListener("click",R);u();let i=1,l="";async function O(o){if(o.preventDefault(),L(),i=1,l=x.value.trim(),!l){a.show({message:"Ну і шо мені шукати? Напиши шось",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}B(),y();try{const e=await f(l,i);e.data.hits.length===0?a.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}):(M(e.data.hits),b())}catch(e){a.show({message:`${e}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{u()}}async function R(o){i+=1,L(),y();try{const e=await f(l,i),n=Math.ceil(e.data.totalHits/15);$(e.data.hits),P(),i<n?b():a.show({message:"We are sorry, but you have reached the end of search results",position:"topRight",backgroundColor:"#6c8cff"})}catch(e){a.show({message:`${e}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{u()}}
//# sourceMappingURL=index.js.map
