import{a as v,S as q,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const M="53452930-453d1b75f98a5875cf6a66d5c";async function h(o,e){return await v("https://pixabay.com/api/",{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})}const u=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector("#load-btn"),m=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){return o.map(({webformatURL:s,largeImageURL:c,tags:t,likes:r,views:i,comments:S,downloads:C})=>`<li class="gallery-item">
      <a class="big-img" href="${c}"><img src="${s}" alt="${t}" width="360px" height="152px" /></a>
      <div class="info">
      <p class="info-descr"><b>Likes:</b> ${r}</p>
      <p class="info-descr"><b>Views:</b> ${i}</p>
      <p class="info-descr"><b>Comments:</b> ${S}</p>
      <p class="info-descr"><b>Downloads:</b> ${C}</p>
      </div>
      </li>`).join("")}function $(o){u.innerHTML=y(o),m.refresh()}function P(o){u.insertAdjacentHTML("beforeend",y(o)),m.refresh()}function k(){u.innerHTML=""}function b(){p.hidden=!1}function f(){p.hidden=!0}function w(){g.classList.replace("load-btn-hidden","search-btn")}function L(){g.classList.replace("search-btn","load-btn-hidden")}function B(){const o=document.querySelectorAll(".gallery-item"),e=o[o.length-15];if(!e)return;const s=e.getBoundingClientRect().top;window.scrollBy({top:s,behavior:"smooth"})}const R=document.querySelector(".form"),x=document.querySelector(".form-input"),H=document.querySelector("#load-btn");document.querySelector(".gallery");R.addEventListener("submit",O);H.addEventListener("click",T);f();let a=1,l,d="";async function O(o){if(o.preventDefault(),L(),a=1,l=null,d=x.value.trim(),!d){n.show({message:"Ну і шо мені шукати? Напиши шось",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}k(),b();try{const e=await h(d,a);if(e.data.hits.length===0)n.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});else{$(e.data.hits);const s=e.config.params.per_page;l=Math.ceil(e.data.totalHits/s),a<l?w():n.show({message:"We are sorry, but you have reached the end of search results",position:"topRight",backgroundColor:"#6c8cff"})}}catch(e){n.show({message:`${e}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{f()}}async function T(o){a+=1,L(),b();try{const e=await h(d,a);P(e.data.hits),B(),a<l?w():n.show({message:"We are sorry, but you have reached the end of search results",position:"topRight",backgroundColor:"#6c8cff"})}catch(e){n.show({message:`${e}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}finally{f()}}
//# sourceMappingURL=index.js.map
